import { Seo } from "@/ui/components/seo/Seo";

export default function Home() {
  return (
    <>
      <Seo title="Coders Monkeys" description="Generated by create next app" />
      <h1>Hello World</h1>
    </>
  );
}
